### Get all users
GET http://127.0.0.1:8000/api/users
Accept: application/json
Authorization: Bearer 4|MgmC1awGSTeK7QhRYtnjmWFATPbKMmO8XLILIkxt16a6288a

### Create a user
POST http://127.0.0.1:8000/api/users
Accept: application/json
Content-Type: application/json

{
    "name": "juan",
    "email": "juan@gmail.com",
    "password": "password123"
}

### Get a user
GET http://127.0.0.1:8000/api/users/4
Accept: application/json

### Update a user
PUT http://127.0.0.1:8000/api/users/4
Accept: application/json
Content-Type: application/json

{
    "name": "Edwin Modificado",
    "email": "edwinjuarez_modificado@gmail.com",
    "password": "password123"
}

### Delete a user
DELETE http://127.0.0.1:8000/api/users/1
Accept: application/json
